source 'https://supermarket.chef.io'

cookbook 'bosting-hosting', path: '../bosting-hosting'
cookbook 'bosting-generator', path: '../bosting-generator'
cookbook 'freebsd', github: 'sekrett/freebsd'
cookbook 'jail', github: 'sekrett/jail'

metadata
