name 'bosting-cp'
maintainer 'Alexander Zubkov'
maintainer_email 'info@zubkov.info'
license 'MIT'
description 'Installs/Configures bosting-cp'
long_description 'Installs/Configures bosting-cp'
version '0.1.0'

depends 'bosting-hosting', '0.1.0'
depends 'bosting-generator', '0.1.0'
depends 'line', '0.6.3'
depends 'freebsd', '1.0.1'
depends 'jail', '0.2.0'
depends 'sysctl', '0.7.5'
depends 'ssh_known_hosts', '2.0.0'
depends 'ruby_rbenv', '1.1.0'
depends 'ruby_build', '1.0.0'
depends 'database', '6.0.0'
depends 'ssl_certificate', '1.11.0'
depends 'ssh_keygen', '1.1.0'
depends 'sudo', '2.11.0'
