name 'bosting-generator'
maintainer 'Alexander Zubkov'
maintainer_email 'info@zubkov.info'
license 'MIT'
description 'Installs/Configures bosting-generator'
long_description 'Installs/Configures bosting-generator'
version '0.1.0'

depends 'line', '0.6.3'
depends 'database', '6.0.0'
depends 'bosting-cp', '0.1.0'
